apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location / {
          proxy_pass http://todo-frontend:80;
          proxy_set_header Host $host;
        }

        location /api/ {
          proxy_pass http://todo-backend:5000/api/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /todos {
          proxy_pass http://todo-backend:5000/todos;
          proxy_set_header Host $host;
        }

        location /metrics {
          proxy_pass http://todo-backend:5000/metrics;
        }
      }
    }

